config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks, :dependent => :destroy

    # Metodo para decidir qual é o progresso atual do projeto com base no status das tarefas
    def status
        return 'Não Iniciado' if tasks.none?

        if tasks.all? { |task| task.complete }
            'Finalizado'
        elsif tasks.any? { |task| task.in_progress}
            'Em progresso'
        else tasks.all? { |task| task.not_started }
            'Não Iniciado'
        end
    end

    # Decidir qual cor do botão será usada com base no andamento do projeto
    def badgecolor
        case status
        when 'Não Iniciado'
            'secondary'
        when 'Em progresso'
            'info'
        when 'Finalizado'
            'success'
        end
    end

    # Calculo da porcentagem do andamento
    def complete
        return 0 if tasks.none?
        tasks_complete = tasks.select { |task| task.complete }.count
        ((tasks_complete.to_f / tasks.count) * 100).round
    end

    # Método para verificar se projeto está atrasado ou não
    def delay
        return "Não Iniciado" if tasks.none?

        if tasks.all? { |task| task.complete }
            'Finalizado'
        elsif tasks.any? { |task| task.delayt}
            'Sim'
        else
            'Não'
        end
    end

end
    

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  validates :status, inclusion: { in: ['Finalizado', 'Em progresso', 'Não Iniciado']}

  STATUS_OPTIONS = [
    ['Não Iniciado', 'Não Iniciado'],
    ['Em progresso', 'Em progresso'],
    ['Finalizado', 'Finalizado']
  ]

  # Metodos para decidir STATUS do projeto
  def complete
  status == 'Finalizado'
  end

  def in_progress
  status == 'Em progresso'
  end

  def not_started
  status == 'Não Iniciado'
  end

  def delayt
  end_date > project.end_date
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # Nostrar todos projetos
  def index
    @projects = Project.all
  end

  # Ir para pagina Novo projeto
  def new
    @project = Project.new
  end

  # Ir para pagina editar
  def edit
  end

  # Criar novo projeto
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # Atualização na opção Editar
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Fatoração + Indicação de ID
    def set_project
      @project = Project.find(params[:id])
    end

    # Permissão de parâmetros autorizados
    def project_params
      params.require(:project).permit(:name, :description, :start_date, :end_date)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_project
  before_action :set_project
  before_action :set_task, only: %i[ show edit update destroy ]

  # Mostrar todas as tarefas
  def index
    @tasks = @project.tasks
  end

  # Ir para Mostrar
  def show
  end

  # Ir para pagina de novo
  def new
    @task = Task.new
  end

  # Ir para pagina Editar
  def edit
  end

  # Criar uma nova tarefa
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_tasks_path(id: @task.id), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # Atualizar na opção Edit
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_tasks_path, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_tasks_path, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Fatoração + Indicação de ID
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @task = Project.find(params[:project_id])
    end
    
    def find_project
      @project = Project.find(params[:project_id])
    end

    # Permissão de parâmetros autorizados
    def task_params
      output = params.require(:task).permit(:name, :description, :start_date, :project_id, :end_date, :status)
      output.merge(project_id: @project.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_footer.html.erb
<footer class="container-fluid text-center">
    <div class="row mt-3" style="background-color: #1d75a7 ">
        <div class="col-sm-4">
            <div class="mt-3">
                <h4> Entre em contato</h4>
                <h5>Nosso endereço e informações de contato</h5>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="mt-3">
                <h4>Siga nas redes sociais</h4>
                <a href="#"><%= image_tag("1350125.png", size: "27x27", :alt => "1350125 feed") %></a>
                <a href="#"><%= image_tag("174855.png", size: "27x27", :alt => "174855 feed") %></a>
                <a href="#"><%= image_tag("linkedin.png", size: "27x27", :alt => "174855 feed") %></a>
                <a href="#"><%= image_tag("twitter.png", size: "27x27", :alt => "twitter feed") %></a>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="">
                <%= image_tag("imagemfooter.png", style:"width: 40%", :alt => "twitter feed") %>
            </div>
        </div>

    </div>

</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style= "background-color:#1d75a7">
  <div class="container-fluid">
    <%= link_to image_tag("logosize.png", size: "192x66" ,:alt => "11077 feed"), root_path %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", projects_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Links Interessantes
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="https://www.linkedin.com/in/milles-schroeder-85144b14b/">Linkedin do programador</a></li>
            <li><a class="dropdown-item" href="https://github.com/MillesDyson">GitHub do programador</a></li>
          </ul>
        </li>
      </ul>
      <form class="form-inline">
        <button type="button" class="btn btn-light landingbutton"><%= link_to "TESTE GRÁTIS!", projects_path, style:"text-decoration: none; color: black" %></button>
      </form>
    </div>
  </div>
</nav>  

app/views/home/index.html.erb
<div id="home">
<div class="padding">
<div>
    <div class="row m-0">
        <div class="col-6 text-center">
            <h1 class="landingtext mt-4">A melhor plataforma para gerenciar seus projetos</h1>
            <h4 >Aumente o poder de gestão da sua empresa</h4>
            <br><button type="button" class="btn btn-light landingbutton"><%= link_to "Comece seu teste agora!", projects_path, style:"text-decoration: none; color: black" %></button>
        </div> 
        <div class="col-6">
            <%= image_tag("31994.png", style:"width: 60%", class: "mx-auto d-block", :alt => "31994 feed") %>
        </div>
    </div>
</div>
</div>

<div class="padding ">
<div>
    <div>
        <div class="row m-0">
            <div class="col-6">
                <div class="m-2  indexblocks">
                    <%= image_tag("6308.jpg", size: "400x250", class: "mx-auto d-block", :alt => "6308 feed") %>
                </div>
            </div>
            <div class="col-6 text-center">
                <div class="m-2  indexblocks">
                    <div>
                        <br><br>
                        <h2>Tudo que você precisa saber sobre nosso gerenciador</h2>
                        <p class=lead>A plataforma de gerenciamento de projetos Millesapp pode ajudar sua empresa a economizar tempo otimizando o controle dos processos</p>
                    </div>
                </div>
            </div>
            
        </div>   
    </div>
</div>
</div>



<div class="padding mb-5">
<div>
    <div>
        <div class="row m-0">
            <div class="col-6 text-center">
                <div class="m-2  indexblocks">
                    <div>
                        <br><br>
                        <h2 class=>Teste nossa plataforma por 1 mês gratuitamente</h2>
                        <p class=lead>
                        Entre em contato para começar seu teste gratis. 
                        Com nossa plataforma de gerenciamento, você pode usar por um mês
                        e já conferir os resultados na sua empresa.</p>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="m-2  indexblocks">
                <%= image_tag("11077.jpg", size: "375x250", class: "mx-auto d-block", :alt => "11077 feed") %>
                </div>
            </div>
        </div>   
    </div>
</div>
</div>
</div>

app/views/layouts/_alertwarn.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href=".\app\assets\stylesheets\home.scss" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Hammersmith+One&display=swap" rel="stylesheet">
   
    <title>Projectmanagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <!-- Inclusão do menu de navegação -->
    <div>
    <%= render 'home/header' %>
    </div>
  
    <!-- Inclusão do style das Alerts -->
    <% if notice %>
      <div class="container mt-3">
         <%= render 'layouts/alertwarn'%>
      </div>
    <% end %>

     <!-- Inclusão do conteúdo de cada página -->
    <div>
    <%= yield %>
    </div>

       <!-- Inclusão do Footer -->
    <div>
    <%= render 'home/footer' %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form|%>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-4">
    <h5>Nome</h5>
    <%= form.text_field :name, class:"form-control"  %>
  </div>

  <div class="field form-group mb-4">
    <h5>Descrição</h5>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div class="field mb-4">
    <h5>Data de Inicio</h5>
    <%= form.date_select :start_date%>
  </div>

  <div class="field mb-4">
    <h5>Data de término</h5>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="container mt-3">
    <div class="row m-3">
        <div class="card mb-3">
            <div class="card-body">
                <h1>Editando projeto</h1>

                <%= render 'form', project: @project %>

                <%= link_to 'Voltar', projects_path, class:"btn btn-primary btn-sm mt-3" %>
            </div>
        </div>
    </div>    
</div>

app/views/projects/index.html.erb
<div class="dashboard">
  <div class="row m-3">
    <div class="col-md-3 mb-3">
      <div class="card ">
         <div class="card-body m-1">
           <h3 class="card-title  text-dar" style="text-align: center">Dashboard</h3>
         </div>
          <div>
              <% @projects.each do |project| %>
                <%= link_to project_tasks_path(project), class:'text-decoration-none' do%>
                  <div class="card m-1">
                    <div class="card-body">
                      <span class="card-title text-dark cardwidth"><b><%= project.name %></b></span><br><span class="badge badge-pill bg-<%= project.badgecolor %>" style="text-align: center"><%= project.status %></span>
                      <br>
                      <div class="progress mt-1 mb-0">
                       <div class="progress-bar" role="progressbar" style="width: <%= project.complete %>%;" aria-valuenow="<%= project.complete %>" aria-valuemin="0" aria-valuemax="100"><%= project.complete %>%
                       </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
          </div>
        </div>
      </div>


  <div class="col-md-9 mb-3">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title mb-3">Projetos</h1>
          <div>
            <table class="table table-light table-hover table-bordered">
              <thead>
                <tr>
                  <th>Nome</th>
                  <th>Descrição</th>
                  <th>Inicio</th>
                  <th>Término</th>
                  <th>Status</th>
                  <th>Progresso</th>
                  <th>Atrasado?</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
          </div>
            <div>
              <tbody>
                <% @projects.each do |project| %>
                  <tr>
                    <td><%= project.name %></td>
                    <td><%= project.description %></td>
                    <td><%= l project.start_date, format: :euro %></td>
                    <td><%= l project.end_date, format: :euro %></td>
                    <td><%= project.status %></td>
                    <td><%= project.complete %>%</td>
                    <td><%= project.delay %></td>
                    <td><%= link_to 'Tarefas', project_tasks_path(project), class:"btn btn-primary btn-sm" %></td>
                    <td><%= link_to 'Editar', edit_project_path(project), class:"btn btn-primary btn-sm" %></td>
                    <td><%= link_to 'Deletar', project, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm"  %></td>
                  </tr>
                <% end %>
              </tbody>
            </div>
          </table>
            <div>
              <%= link_to 'Novo Projeto', new_project_path, class:"btn btn-primary btn-sm mb-3"%>
            </div>
          </div>
      </div>
  </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container mt-3 mb-3">
    <div class="row m-3">   
        <div class="card mb-3">
            <div class="card-body">
                <h1 class="card-title mb-2">Novo Projeto</h1>

                <%= render 'form', project: @project %>

                <%= link_to 'Voltar', projects_path, class:"btn btn-primary btn-sm mt-3" %>
            </div>
        </div>
    </div>
</div>

app/views/projects/show.html.erb
<div class="container">

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @project.end_date %>
</p>


<%= link_to 'View All Tasks', project_tasks_path(project_id: @project.id) %>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@project, @task]) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mb-4">
    <h5>Nome</h5>
    <%= form.text_field :name, class:"form-control"  %>
  </div>

  <div class="field form-group mb-4">
    <h5>Descrição</h5>
    <%= form.text_area :description, class:"form-control"  %>
  </div>

  <div class="field mb-4">
    <h5>Data de Inicio</h5>
    <%= form.date_select :start_date %>
  </div>

  <div class="field mb-4">
    <h5>Data de Término</h5>
    <%= form.date_select :end_date %>
  </div>

  <div class="field mb-4">
    <h5>Status</h5>
    <%= form.select :status, Task::STATUS_OPTIONS %>
    
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary btn-sm mt-3" %>
  </div>


<% end %>

app/views/tasks/edit.html.erb
<div class="container mt-3">
   <div class="row m-3">
        <div class="card mb-3">
            <div class="card-body">
                <h1>Editing Task</h1>

                <%= render 'form', task: @task %>
                <%= link_to 'Back', project_tasks_path, class:"btn btn-primary btn-sm mt-3" %>
            </div>
        </div>
    </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row m-3">
      <div class="card mb-3">
        <div class="card-body">
          <h1>Tarefas</h1>

          <table class="table table-light table-hover table-bordered">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Inicio</th>
                <th>Término</th>
                <th>Status</th>
                <th>Projeto ID</th>
                <th colspan="2"></th>
              </tr>
            </thead>

            <tbody>
              <% @tasks.each do |task| %>
                <tr>
                  <td><%= task.name %></td>
                  <td><%= task.description %></td>
                  <td><%= l task.start_date, format: :euro  %></td>
                  <td><%= l task.end_date, format: :euro %></td>
                  <td><%= task.status %></td>
                  <td><%= task.project_id %></td>
                  <td><%= link_to 'Editar', edit_project_task_path(@project, task), class:"btn btn-primary btn-sm"  %></td>
                  <td><%= link_to 'Deletar', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
                </tr>
              <% end %>
            </tbody>
            <tfoot>
            </tfoot>
          </table>

          <div>
            <%= link_to 'Nova tarefa', new_project_task_path, class:"btn btn-primary btn-sm mb-3" %>
            <%= link_to 'Voltar', projects_path, class:"btn btn-primary btn-sm mb-3" %>
          </div>
        </div>
        </div>
        </div>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container mt-3 mb-3">
   <div class="row m-3">
        <div class="card mb-3">
            <div class="card-body">
                <h1>Nova tarefa</h1>

                <%= render 'form', task: @task %>

                <%= link_to 'Voltar', project_tasks_path, class:"btn btn-primary btn-sm mt-3" %>
            </div>
        </div>
    </div>
</div>

app/views/tasks/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Project:</strong>
  <%= @task.project_id %>
</p>

<%= link_to 'Edit', edit_project_task_path(@project, @task) %> |
<%= link_to 'Back', project_tasks_path %>